apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-app
  template:
    metadata:
      labels:
        app: sales-app
    spec:
      containers:
        - name: sales-app
          image: bhanujoshi241999/sales-app:gcp-1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5051
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
