apiVersion: v1
kind: Service
metadata:
  name: mailhog-service
  namespace: hash-backend
spec:
  selector:
    app: mailhog
  ports:
    - name: smtp  # Name for the first port
      protocol: TCP
      port: 8025
      targetPort: 8025
    - name: http  # Name for the second port
      protocol: TCP
      port: 1025
      targetPort: 1025
  type: LoadBalancer